export const GlobalVariable = Object.freeze({
    BASE_API_URL: "http://localhost:8080/Api/rest",
    THEME_API: 'light-blue lighten-2',
    COLOR_TITLE: '#004d40',
    PARAMS_DATE : [{ selectMonths: true,
        monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sabádo'],
        weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
        today: 'Hoje',
        clear: 'Limpar',
        close: 'Fechar',
        editable: false,
        labelMonthNext: 'Próximo mês',
        labelMonthPrev: 'Mês anterior',
        format: 'dd/mm/yyyy',
        closeOnSelect: true,       
        selectYears: 15
    }],     
});