export const StatusSolicitacaoConst = Object.freeze({
    ABERTO: "ABERTO",
    PLANEJADO: "PLANEJADO",
    EXECUCAO: "EXECUÇÃO",
    CONCLUIDO: "CONCLUÍDO",
    CANCELADO: "CANCELADO",
    AGUARDANDO_INFORMACAO: "AGUARDANDO INFORMAÇÃO"
});